# -*- coding: utf-8 -*-
"""Introdução ao Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Briqz23/7e42c16d09bad5215f591f4d0422cb06/introdu-o-ao-data-science.ipynb
"""

import pandas as pd

pd.read_csv("ratings.csv")

notas = pd.read_csv("ratings.csv")

#vai mostrar as 5 primeiras tuplas
notas.head()

#diz quantas linhas e colunas tem
notas.shape

#renomeia atributos
notas.columns = ["usuarioID", "filmeID", "nota", "momento"]

#mostra todos os valores únicos referentes ao atributo nota
notas["nota"].unique()

#mostra a quantidade de valores dados para cada repeticao de nota
notas['nota'].value_counts()

#ver media 
notas['nota'].mean()

