# -*- coding: utf-8 -*-
"""Introdução ao Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byJgOSxnrbZcFCSx52xJkBEwSbxvM1j8

#Entrada de valores
"""

import pandas as pd
import seaborn as sns
filmes = pd.read_csv("movies.csv")
notas = pd.read_csv("ratings.csv")
notas.columns = ["usuarioID", "filmeID", "nota", "momento"]
filmes.columns = ["filmeID", "titulo", "generos"]

"""#Comandos Gerais (01)

"""

pd.read_csv("ratings.csv")

notas = pd.read_csv("ratings.csv")

#vai mostrar as 5 primeiras tuplas
notas.head()

#diz quantas linhas e colunas tem
notas.shape

#renomeia atributos
notas.columns = ["usuarioID", "filmeID", "nota", "momento"]

#mostra todos os valores únicos referentes ao atributo nota
notas["nota"].unique()

#mostra a quantidade de valores dados para cada repeticao de nota
notas['nota'].value_counts()

#ver media 
notas['nota'].mean()

"""#Histograma e Boxplot"""

#Histograma
notas.nota.plot(kind='hist')
notas.nota.describe
#ou (bins são as barras) e, se fosse y, giraria 90 graus

import seaborn as sns
medias_por_filme = notas.groupby("filmeID").mean()["nota"]
sns.distplot(x=medias_por_filme, bins = 5)

#Boxplot
import matplotlib.pyplot as plt
plt.hist(medias_por_filme)
plt.title("Esse é um boxplot com a biblioteca pyplot")
#ou
import seaborn as sns
sns.boxplot(notas.nota)

"""#Queries groupby e "select""""

#select notas.nota from nota where filmeID==1
notas.query("filmeID == 1").nota

#saber a média dos filmes cujo ID é 1:
notas.query("filmeID == 1").nota.mean()

#agrupamento de IDs para saber a média de cada um
notas.groupby("filmeID").mean()

#agrupamento de IDs para saber a média de cada um + "select" de nota
medias_por_filme = notas.groupby("filmeID").mean()["nota"]

#histograma das médias de filmes  
medias_por_filme.plot(kind = "hist")

#boxplot, distrubuiçao da média dos filmes, os quais estão agrupados por ID | obs: executar sem o comando acima, bug. 
print(sns.boxplot(medias_por_filme))

#o 50% é a mediana
medias_por_filme.describe()