# -*- coding: utf-8 -*-
"""Introdução ao Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byJgOSxnrbZcFCSx52xJkBEwSbxvM1j8
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")

notas.columns = ["usuarioID", "filmeID", "nota", "momento"]

#Histograma
notas.nota.plot(kind='hist')
notas.nota.describe

#Boxplot

import seaborn as sns
print(sns.boxplot(notas.nota))