# -*- coding: utf-8 -*-
"""03_Classificações _Variáveis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Briqz23/7e42c16d09bad5215f591f4d0422cb06/introdu-o-ao-data-science.ipynb
"""

import pandas as pd

tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb.head()

"""```
nominal, ex: idiomas dos filmes. Não existe uma ordem, são categorias que não são comparáveis.

ordinal, ex: primeiro colegial, segundo colegial e terceiro colegial. Seguem uma ordem, mas não é aritimética. Não posso dizer que terceiro colegial é três vezes maior que o primeiro. Ou que a distância do primeiro colegial pro segundo é igual a do segundo pro terceiro.

quantitativo contínuo: budget do filme. Existem intervalos entre os budgets, como 200 KK <2500K260 < 300KK

quantitativa intervalar, ex: votos. Não existe intervalo entre eles. Não existe nota 2.33, só 2 e 2.5

"""