# -*- coding: utf-8 -*-
"""05_Exemplos_Media_mediana_histograma_boxplot_desvio padrão

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byJgOSxnrbZcFCSx52xJkBEwSbxvM1j8

#Entrada de valores
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
filmes = pd.read_csv("movies.csv")
notas = pd.read_csv("ratings.csv")

notas_do_toy_story = notas.query("movieId==1")
notas_da_jumanji = notas.query("movieId==2")
#imprimir quantas notas tem de cada:
print(len(notas_do_toy_story), len(notas_da_jumanji))

print(f"Nota média do Toy Story : {notas_do_toy_story.rating.mean():.2f} \nNota média da Jumanji : {notas_da_jumanji.rating.mean():.2f} ")

print(f"\nMediana das notas do Toy Story : {notas_do_toy_story.rating.median():.2f} \nMediana das notas da Jumanji : {notas_da_jumanji.rating.median():.2f} ")

#Exemplo do pq que mediana e média podem ser pouco representativas:

ArrayNotasfilme1 = np.append(np.array([2.5]*10),np.array([3.5]*10)) #gostaram +-
ArrayNotasfilme2 = np.append(np.array([1]*10), np.array([5]*10)) #amaram ou odiaram o filme

#mesmo resultado...
print(ArrayNotasfilme1.mean(), ArrayNotasfilme2.mean())
print(np.median(ArrayNotasfilme1), np.median(ArrayNotasfilme2))

#cálculo do desvio padrão. Isso é um bom índice para saber o quão díspares as notas estão

print(np.std(ArrayNotasfilme1), np.std(ArrayNotasfilme2))

#essa seria uma boa referência de gráfico
plt.hist(ArrayNotasfilme2)
plt.hist(ArrayNotasfilme1)

#ou também.. com boxplot da biblioteca do pyplot
plt.boxplot([ArrayNotasfilme1,ArrayNotasfilme2])

#no exemplo csv ficaria assim com seaborn:
sns.boxplot(x = "movieId", y = "rating", data = notas.query("movieId in (1,2,3,4,5)"))



